#!/bin/bash

if ! command -v python3 &> /dev/null; then
    python -m http.server --directory lightbeam-core/target/scala-3.1.0/api/
else
    python3 -m http.server --directory lightbeam-core/target/scala-3.1.0/api/
fi
